# Generated by Django 5.1.6 on 2025-02-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pax', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Kebun'), ('shopeepay', 'ShopeePay'), ('bri', 'Bank BRI'), ('bca', 'Bank BCA')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
