# Generated by Django 5.1.6 on 2025-02-21 13:04

from django.db import migrations, models
import uuid

def generate_unique_booking_code(apps, schema_editor):
    Booking = apps.get_model("booking", "Booking")
    for booking in Booking.objects.all():
        booking.booking_code = str(uuid.uuid4().hex[:8]).upper()
        booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_code",
            field=models.CharField(max_length=10, unique=True, blank=True),
        ),
        migrations.RunPython(generate_unique_booking_code),
    ]
